/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Model.*;

/**
 *
 * @author Miguemc
 */
public class DeathBadConsequenceView extends javax.swing.JPanel {
    DeathBadConsequence deathBadConsequenceModel;
    /**
     * Creates new form BadConsequenceView
     */
    public DeathBadConsequenceView() {
        initComponents();
    }
    
    public void setDeathBadConsequence(DeathBadConsequence bc){
        deathBadConsequenceModel = bc;
        text.setText(deathBadConsequenceModel.getText());
        death.setText(Boolean.toString(deathBadConsequenceModel.kills()));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textD = new javax.swing.JLabel();
        deathD = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        death = new javax.swing.JLabel();

        textD.setText("Text");

        deathD.setText("Death");

        text.setText("jLabel3");

        death.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textD)
                        .addGap(26, 26, 26)
                        .addComponent(text))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deathD)
                        .addGap(18, 18, 18)
                        .addComponent(death)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textD)
                    .addComponent(text))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deathD)
                    .addComponent(death))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel death;
    private javax.swing.JLabel deathD;
    private javax.swing.JLabel text;
    private javax.swing.JLabel textD;
    // End of variables declaration//GEN-END:variables
}
