/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Model.Treasure;


/**
 *
 * @author Miguel Morales Castillo y María del Mar Ruiz Martín
 */
public class TreasureView extends javax.swing.JPanel {
    private Treasure treasureModel;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();         
    }
    
    public void setTreasure (Treasure t) {
        treasureModel = t;
        goldCoins.setText(Integer.toString(treasureModel.getGoldCoins()));
        name.setText(treasureModel.getName());
        type.setText(treasureModel.getType().toString());
        minBonus.setText(Integer.toString(treasureModel.getBasicBalue()));
        maxBonus.setText(Integer.toString(treasureModel.getSpecialValue()));
        // Se supone que el JLabel que se ha creado para mostrar el valor en
        // piezas de oro del tesoro se ha denominado coins
        // Proceder de manera similar con el resto de componentes
        // Finalizar con la siguiente orden para que los cambios se hagan
        // efectivos
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameD = new javax.swing.JLabel();
        typeD = new javax.swing.JLabel();
        minBonusD = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        minBonus = new javax.swing.JLabel();
        maxBonusD = new javax.swing.JLabel();
        maxBonus = new javax.swing.JLabel();
        goldCoinsD = new javax.swing.JLabel();
        goldCoins = new javax.swing.JLabel();

        nameD.setText("Name");

        typeD.setText("Type");

        minBonusD.setText("MinBonus");

        name.setText("jLabel4");

        type.setText("jLabel5");

        minBonus.setText("jLabel6");

        maxBonusD.setText("MaxBonus");

        maxBonus.setText("jLabel8");

        goldCoinsD.setText("GoldCoinsValue");

        goldCoins.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(minBonusD)
                                .addComponent(typeD)
                                .addComponent(nameD))
                            .addGap(22, 22, 22))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(maxBonusD)
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(goldCoinsD)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goldCoins)
                    .addComponent(maxBonus)
                    .addComponent(name)
                    .addComponent(type)
                    .addComponent(minBonus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameD)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeD)
                    .addComponent(type))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minBonusD)
                    .addComponent(minBonus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxBonusD)
                    .addComponent(maxBonus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goldCoinsD)
                    .addComponent(goldCoins))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goldCoins;
    private javax.swing.JLabel goldCoinsD;
    private javax.swing.JLabel maxBonus;
    private javax.swing.JLabel maxBonusD;
    private javax.swing.JLabel minBonus;
    private javax.swing.JLabel minBonusD;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameD;
    private javax.swing.JLabel type;
    private javax.swing.JLabel typeD;
    // End of variables declaration//GEN-END:variables
}
