/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Model.Treasure;


/**
 *
 * @author Miguel Morales Castillo y María del Mar Ruiz Martín
 */
public class TreasureView extends javax.swing.JPanel {
    
    private Treasure treasureModel;
    private boolean selected = false;
    
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();         
    }
    
    public void setTreasure (Treasure t) {
        treasureModel = t;
        goldCoins.setText(Integer.toString(treasureModel.getGoldCoins()));
        name.setText(treasureModel.getName());
        type.setText(treasureModel.getType().toString());
        minBonus.setText(Integer.toString(treasureModel.getBasicValue()));
        maxBonus.setText(Integer.toString(treasureModel.getSpecialValue()));

        repaint();
    }

    public boolean isSelected(){
        return this.selected;
    }
    
    public Treasure getTreasure(){
        return this.treasureModel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeD = new javax.swing.JLabel();
        minBonusD = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        minBonus = new javax.swing.JLabel();
        maxBonusD = new javax.swing.JLabel();
        maxBonus = new javax.swing.JLabel();
        goldCoinsD = new javax.swing.JLabel();
        goldCoins = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        typeD.setText("Type");

        minBonusD.setText("MinBonus");

        name.setText("jLabel4");

        type.setText("jLabel5");

        minBonus.setText("jLabel6");

        maxBonusD.setText("MaxBonus");

        maxBonus.setText("jLabel8");

        goldCoinsD.setText("GoldCoinsValue");

        goldCoins.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(goldCoinsD)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maxBonusD)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(minBonusD)
                                .addComponent(typeD)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBonus)
                    .addComponent(goldCoins)
                    .addComponent(minBonus)
                    .addComponent(type))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeD)
                    .addComponent(type))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minBonusD)
                    .addComponent(minBonus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxBonusD)
                    .addComponent(maxBonus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goldCoinsD)
                    .addComponent(goldCoins))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.selected = !this.selected;
        setBackground(new java.awt.Color(250,0,100));
        setOpaque(selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goldCoins;
    private javax.swing.JLabel goldCoinsD;
    private javax.swing.JLabel maxBonus;
    private javax.swing.JLabel maxBonusD;
    private javax.swing.JLabel minBonus;
    private javax.swing.JLabel minBonusD;
    private javax.swing.JLabel name;
    private javax.swing.JLabel type;
    private javax.swing.JLabel typeD;
    // End of variables declaration//GEN-END:variables
}
